### ISSUE TITLE
В блок с табами добавить новый раздел

### ISSUE THREAD

**Issue by natagolovkina** [natagolovkina/forzip#3]
К табам (Главная Каталог Onlineзаявка Контакты) добавить новый раздел: обслуживание

Должно быть так: Главная Каталог Обслуживание Online заявка Контакты

**Comment by DenSpar** [comment]
это легко, добавлю сразу на стадии создания скелета

**Comment by DenSpar** [comment]
готово

**Comment by natagolovkina** [comment]
> готово

Где PR?

**Comment by natagolovkina** [comment]
сделано в #1
