### ISSUE TITLE
Главная

### ISSUE THREAD

**Issue by natagolovkina** [natagolovkina/forzip#7]
Главная:
* в шапке: лого - Форзип Москва - блок поиска по сайту - кликабельный телефон - кликабельная почта
* шапка при скролле должна залипать (лого (?), название, поиск, онлайн заявка, телефон, почта)
* под описание вставляем пресет с этими картинками https://yadi.sk/i/1GxkePX8tHuRWg
* под пресет с марками вставляем самодвижущийся пресет "наши товары", который бкдет двигаться не сверху вниз, а слева направо https://yadi.sk/i/hbWn-oDoqKXc-g
* онлайн заявку убираем 
* меню внизу убираем
* из футера поиск по сайту убираем

#343a40 шапка 16px заголовок , 18px телефон
#f8f9fa меню, текст 18px
#e9ecef основной фон, текст 16px
#f8f9fa футер
#2196f3 - выбранная вкладка меню
бордер радиус 4px везде, кроме шапки и футера

![2020-03-18_16-01-54](https://user-images.githubusercontent.com/32706668/76963392-01574800-6932-11ea-961a-7e1194ba589a.png)

**Comment by DenSpar** [comment]
принято в работу

**Comment by DenSpar** [comment]
- кликабельный телефон и адрес сделал
- перенес онлайн заявку в шапку
- добавил иконки в онлайн заявку и поиск
-внизу онлайн заявку, меню и поиск убрал

**Comment by natagolovkina** [comment]
Обновила макет

**Comment by DenSpar** [comment]
сделал:
1) фон шапки #343a40
2) заголовок шапки размером 16px
3) контакты размером 14px, (18px очень большие)
4) фон меню #f8f9fa
5) текст меню 18px
6) фон основного контента #e9ecef
7) заголовок в основном контенте 20px, текст 16px
8) бренды переместил в низ блока контента, карусель товаров рядом с описанием
9) вместо карусели пока заглушка
10 фон футера #f8f9fa
11) текст в шапке белым цветом, в остальных местах текст цвета фона шапки
12) добавил картинку для темной шапки для заявки

еще осталось:
1) сделать цвет текста #2196f3 у выбранной вкладки меню
2) бордер радиус 4px везде, кроме шапки и футера - буду править по факту
3) убрать иконку "оставить заявку" из шапки, сделать чтобы она появлялась при скроле вниз

З.Ы. поиск по сайту в футере решили оставить

**Comment by DenSpar** [comment]
запушил новые изменения:
1) высоту шапки сделал больше
2) высоту строки меню уменьшил до значения высоты шапки
3) увеличил заглушку карусели товаров по ширине
4) выровнял по левому краю контент шапки, меню и описания
5) увеличил отступ сверху в блоке контента
6) увеличил расстояние между марками и "каруселью"
7) сделал фон карточек марок белым, чтобы не было видно что картинки разного размера
  + изменил картинку Berg
8) убрал из футера название + увеличил отступы футера

бордер радиусы решили не менять

осталось:
1) убрать иконку "оставить заявку" из шапки, сделать чтобы она появлялась при скроле вниз
2) сделать цвет текста #2196f3 у выбранной вкладки меню (предлагаю выделить в отдельную задачу, выполнять после того как будет несколько страниц)

**Comment by natagolovkina** [comment]
* определились, что бордер радиус 4px везде, где он есть, кроме марок. У марок 12px
* бордер у всех элементов 1px
* строка поиска - высоту увеличить до 30px и убрать фон
* блок контактов в шапке справа - выровнять справа
* марки растянуть больше, на 90%
* названия в две строки у марок слиплись, нужно сделать отступ
* блок марок спустить еще на 40px вниз
* карта сайта - сделать шрифт и цвет #e9ecef
* сделать ограничения на ширину экрана, чтобы все не расползалось
* cделать pointer на марки и какой-то ховер (не придумала еще)

**Comment by natagolovkina** [comment]
> 2. сделать цвет текста #2196f3 у выбранной вкладки меню (предлагаю выделить в отдельную задачу, выполнять после того как будет несколько страниц)

Давай

**Comment by DenSpar** [comment]
сделать отдельные задачи:
1) сделать ограничения на ширину экрана, чтобы все не расползалось. Но предусмотреть, чтобы бэкгроунд шапки и меню доходила до края экрана
2) cделать какой-то ховер для марок. Возможно тень
